name: Pro ISP Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ssh.c4sbr7xzy.service.one
          username: ${{ secrets.PROISP_SFTP_USERNAME }}
          # or store host/username in secrets as well
          password: ${{ secrets.PROISP_SFTP_PASSWORD }}
          port: 22 # default SSH port
          source: "public/*" # everything from 'public'
          target: "/domains/dgputt.app/webroot/r1164085"
          overwrite: true # overwrite existing files
          rm: false # do NOT remove extra files/folders

