name: Pro ISP Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ssh.c4sbr7xzy.service.one
          protocol: sftp
          username: ${{ secrets.PROISP_SFTP_USERNAME }}
          password: ${{ secrets.PROISP_SFTP_PASSWORD }}
          local-dir: public
          server-dir: /domains/dgputt.app/webroot/r1164085
          exclude: |
            charlotte*
